// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Puissance4.Business
{
    public partial class MLP4Model
    {
        /// <summary>
        /// model input class for MLP4Model.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Pos01")]
            public float Pos01 { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Pos02")]
            public float Pos02 { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Pos03")]
            public float Pos03 { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Pos04")]
            public float Pos04 { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Pos05")]
            public float Pos05 { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Pos06")]
            public float Pos06 { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Pos07")]
            public float Pos07 { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Pos08")]
            public float Pos08 { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Pos09")]
            public float Pos09 { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Pos10")]
            public float Pos10 { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"Pos11")]
            public float Pos11 { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"Pos12")]
            public float Pos12 { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"Pos13")]
            public float Pos13 { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"Pos14")]
            public float Pos14 { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"Pos15")]
            public float Pos15 { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"Pos16")]
            public float Pos16 { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"Pos17")]
            public float Pos17 { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"Pos18")]
            public float Pos18 { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"Pos19")]
            public float Pos19 { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"Pos20")]
            public float Pos20 { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"Pos21")]
            public float Pos21 { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"Pos22")]
            public float Pos22 { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"Pos23")]
            public float Pos23 { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"Pos24")]
            public float Pos24 { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"Pos25")]
            public float Pos25 { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"Pos26")]
            public float Pos26 { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"Pos27")]
            public float Pos27 { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"Pos28")]
            public float Pos28 { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"Pos29")]
            public float Pos29 { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"Pos30")]
            public float Pos30 { get; set; }

            [LoadColumn(30)]
            [ColumnName(@"Pos31")]
            public float Pos31 { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"Pos32")]
            public float Pos32 { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"Pos33")]
            public float Pos33 { get; set; }

            [LoadColumn(33)]
            [ColumnName(@"Pos34")]
            public float Pos34 { get; set; }

            [LoadColumn(34)]
            [ColumnName(@"Pos35")]
            public float Pos35 { get; set; }

            [LoadColumn(35)]
            [ColumnName(@"Pos36")]
            public float Pos36 { get; set; }

            [LoadColumn(36)]
            [ColumnName(@"Pos37")]
            public float Pos37 { get; set; }

            [LoadColumn(37)]
            [ColumnName(@"Pos38")]
            public float Pos38 { get; set; }

            [LoadColumn(38)]
            [ColumnName(@"Pos39")]
            public float Pos39 { get; set; }

            [LoadColumn(39)]
            [ColumnName(@"Pos40")]
            public float Pos40 { get; set; }

            [LoadColumn(40)]
            [ColumnName(@"Pos41")]
            public float Pos41 { get; set; }

            [LoadColumn(41)]
            [ColumnName(@"Pos42")]
            public float Pos42 { get; set; }

            [LoadColumn(42)]
            [ColumnName(@"Winner")]
            public float Winner { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLP4Model.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Pos01")]
            public float Pos01 { get; set; }

            [ColumnName(@"Pos02")]
            public float Pos02 { get; set; }

            [ColumnName(@"Pos03")]
            public float Pos03 { get; set; }

            [ColumnName(@"Pos04")]
            public float Pos04 { get; set; }

            [ColumnName(@"Pos05")]
            public float Pos05 { get; set; }

            [ColumnName(@"Pos06")]
            public float Pos06 { get; set; }

            [ColumnName(@"Pos07")]
            public float Pos07 { get; set; }

            [ColumnName(@"Pos08")]
            public float Pos08 { get; set; }

            [ColumnName(@"Pos09")]
            public float Pos09 { get; set; }

            [ColumnName(@"Pos10")]
            public float Pos10 { get; set; }

            [ColumnName(@"Pos11")]
            public float Pos11 { get; set; }

            [ColumnName(@"Pos12")]
            public float Pos12 { get; set; }

            [ColumnName(@"Pos13")]
            public float Pos13 { get; set; }

            [ColumnName(@"Pos14")]
            public float Pos14 { get; set; }

            [ColumnName(@"Pos15")]
            public float Pos15 { get; set; }

            [ColumnName(@"Pos16")]
            public float Pos16 { get; set; }

            [ColumnName(@"Pos17")]
            public float Pos17 { get; set; }

            [ColumnName(@"Pos18")]
            public float Pos18 { get; set; }

            [ColumnName(@"Pos19")]
            public float Pos19 { get; set; }

            [ColumnName(@"Pos20")]
            public float Pos20 { get; set; }

            [ColumnName(@"Pos21")]
            public float Pos21 { get; set; }

            [ColumnName(@"Pos22")]
            public float Pos22 { get; set; }

            [ColumnName(@"Pos23")]
            public float Pos23 { get; set; }

            [ColumnName(@"Pos24")]
            public float Pos24 { get; set; }

            [ColumnName(@"Pos25")]
            public float Pos25 { get; set; }

            [ColumnName(@"Pos26")]
            public float Pos26 { get; set; }

            [ColumnName(@"Pos27")]
            public float Pos27 { get; set; }

            [ColumnName(@"Pos28")]
            public float Pos28 { get; set; }

            [ColumnName(@"Pos29")]
            public float Pos29 { get; set; }

            [ColumnName(@"Pos30")]
            public float Pos30 { get; set; }

            [ColumnName(@"Pos31")]
            public float Pos31 { get; set; }

            [ColumnName(@"Pos32")]
            public float Pos32 { get; set; }

            [ColumnName(@"Pos33")]
            public float Pos33 { get; set; }

            [ColumnName(@"Pos34")]
            public float Pos34 { get; set; }

            [ColumnName(@"Pos35")]
            public float Pos35 { get; set; }

            [ColumnName(@"Pos36")]
            public float Pos36 { get; set; }

            [ColumnName(@"Pos37")]
            public float Pos37 { get; set; }

            [ColumnName(@"Pos38")]
            public float Pos38 { get; set; }

            [ColumnName(@"Pos39")]
            public float Pos39 { get; set; }

            [ColumnName(@"Pos40")]
            public float Pos40 { get; set; }

            [ColumnName(@"Pos41")]
            public float Pos41 { get; set; }

            [ColumnName(@"Pos42")]
            public float Pos42 { get; set; }

            [ColumnName(@"Winner")]
            public float Winner { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLP4Model.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
